IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Employee') 
BEGIN 
    ALTER TABLE Employee
    ADD IsDeleted INTEGER NOT NULL DEFAULT 0;
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Issue') 
BEGIN 
    ALTER TABLE Issue
    ADD IsDeleted INTEGER NOT NULL DEFAULT 0;
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Project') 
BEGIN 
    ALTER TABLE Project
    ADD IsDeleted INTEGER NOT NULL DEFAULT 0;
    ALTER TABLE Project
    DROP CONSTAINT UQ__Project__D932E92CB2EBD10F;
    ALTER TABLE Project
    ALTER COLUMN ShortName NVARCHAR(255) NOT NULL;
END

