//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IssueResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IssueResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskManager.Resources.IssueResource", typeof(IssueResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Date.
        /// </summary>
        public static string BeginDate {
            get {
                return ResourceManager.GetString("BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter begin date.
        /// </summary>
        public static string BeginDatePlaceholder {
            get {
                return ResourceManager.GetString("BeginDatePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;BeginDate&quot; is required.
        /// </summary>
        public static string BeginDateRequired {
            get {
                return ResourceManager.GetString("BeginDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create issue.
        /// </summary>
        public static string CreateIssue {
            get {
                return ResourceManager.GetString("CreateIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date format is not valid.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin date cannot be later then end date.
        /// </summary>
        public static string EarlierDate {
            get {
                return ResourceManager.GetString("EarlierDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit issue.
        /// </summary>
        public static string EditIssue {
            get {
                return ResourceManager.GetString("EditIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDate.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter end date.
        /// </summary>
        public static string EndDatePlaceholder {
            get {
                return ResourceManager.GetString("EndDatePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;EndDate&quot; is required.
        /// </summary>
        public static string EndDateRequired {
            get {
                return ResourceManager.GetString("EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee.
        /// </summary>
        public static string IssueEmployee {
            get {
                return ResourceManager.GetString("IssueEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select assignee.
        /// </summary>
        public static string IssueEmployeePlaceholder {
            get {
                return ResourceManager.GetString("IssueEmployeePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Assignee&quot; is required.
        /// </summary>
        public static string IssueEmployeeRequired {
            get {
                return ResourceManager.GetString("IssueEmployeeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue is not found by id .
        /// </summary>
        public static string IssueNotFoundById {
            get {
                return ResourceManager.GetString("IssueNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string IssueProject {
            get {
                return ResourceManager.GetString("IssueProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select project.
        /// </summary>
        public static string IssueProjectPlaceholder {
            get {
                return ResourceManager.GetString("IssueProjectPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Project&quot; is required.
        /// </summary>
        public static string IssueProjectRequired {
            get {
                return ResourceManager.GetString("IssueProjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        public static string Issues {
            get {
                return ResourceManager.GetString("Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues list.
        /// </summary>
        public static string IssuesList {
            get {
                return ResourceManager.GetString("IssuesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues are not found.
        /// </summary>
        public static string IssuesNotFound {
            get {
                return ResourceManager.GetString("IssuesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date cannot be later then 31-12-9999.
        /// </summary>
        public static string MaxDate {
            get {
                return ResourceManager.GetString("MaxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date cannot be earlier then 01-01-1900.
        /// </summary>
        public static string MinDate {
            get {
                return ResourceManager.GetString("MinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name should contain maximum 255 characters.
        /// </summary>
        public static string NameLong {
            get {
                return ResourceManager.GetString("NameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write name.
        /// </summary>
        public static string NamePlaceholder {
            get {
                return ResourceManager.GetString("NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Name&quot; is required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select status.
        /// </summary>
        public static string StatusPlaceholder {
            get {
                return ResourceManager.GetString("StatusPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Status&quot; is required.
        /// </summary>
        public static string StatusRequired {
            get {
                return ResourceManager.GetString("StatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        public static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work hours should be between 1 and 1000000.
        /// </summary>
        public static string WorkInvalid {
            get {
                return ResourceManager.GetString("WorkInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter work (natural numbers).
        /// </summary>
        public static string WorkPlaceholder {
            get {
                return ResourceManager.GetString("WorkPlaceholder", resourceCulture);
            }
        }
    }
}
